name: build-collection-index
on:
  pull_request:
    branches:
      - master
jobs:
  create_index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Compile index.json from collections in ~/api
        run: node ./buildCollectionIndex.js
      - name: git - set identity
        run: |
          git config user.email "silentarcticdev@gmail.com"
          git config user.name "SilentArctic"
      - name: commit and push changes
        run: |
          git add api/index.json
          git status
          git commit -m "[ACTION] recreate collection index"
          git push
